name: auto deploy CI/CD

on:
  push:
    branches:
      - main
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - LICENSE

jobs:
  build-production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x] # 配置所需node版本
    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，检出仓库副本
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} #规定node.js版本(可不配置)
      - name: Install dependencies # 第二步，安装依赖
        run: npm install yarn && yarn
      - name: Build # 第三步，打包代码
        run: yarn build
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
